"""Initial Migration

Revision ID: 034a954df9fc
Revises: cc2b872ec2fa
Create Date: 2018-07-03 08:58:33.101163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034a954df9fc'
down_revision = 'cc2b872ec2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'pitch')
    op.add_column('pitches', sa.Column('body', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('pitches', 'pitch')
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'body')
    op.add_column('comments', sa.Column('pitch', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
